  on:
    push:
      branches:
        - master
  jobs:
    build:
      name: "Get Secret"
      runs-on: ubuntu-latest
      permissions:
        contents: read
        id-token: write
      steps:
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v0.4.0'
          with:
            token_format: 'access_token'
            workload_identity_provider: 'projects/511751612237/locations/global/workloadIdentityPools/duckpond/providers/duckmaker'
            service_account: 'konnektor@abels-magical-playground.iam.gserviceaccount.com'

        - name: 'Access secret'
          run: |-
            curl https://secretmanager.googleapis.com/v1/projects/511751612237/secrets/webhook-secret/versions/1:access \
              --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"